# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from obstacle_detect/LidarObstacleInfoArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import obstacle_detect.msg

class LidarObstacleInfoArray(genpy.Message):
  _md5sum = "55f01341e34384ade81bbed242fb4d66"
  _type = "obstacle_detect/LidarObstacleInfoArray"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """LidarObstacleInfo[] obstacle_infos
================================================================================
MSG: obstacle_detect/LidarObstacleInfo
float32 obst_x
float32 obst_y"""
  __slots__ = ['obstacle_infos']
  _slot_types = ['obstacle_detect/LidarObstacleInfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       obstacle_infos

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LidarObstacleInfoArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.obstacle_infos is None:
        self.obstacle_infos = []
    else:
      self.obstacle_infos = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.obstacle_infos)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacle_infos:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.obst_x, _x.obst_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.obstacle_infos is None:
        self.obstacle_infos = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacle_infos = []
      for i in range(0, length):
        val1 = obstacle_detect.msg.LidarObstacleInfo()
        _x = val1
        start = end
        end += 8
        (_x.obst_x, _x.obst_y,) = _get_struct_2f().unpack(str[start:end])
        self.obstacle_infos.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.obstacle_infos)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacle_infos:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.obst_x, _x.obst_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.obstacle_infos is None:
        self.obstacle_infos = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacle_infos = []
      for i in range(0, length):
        val1 = obstacle_detect.msg.LidarObstacleInfo()
        _x = val1
        start = end
        end += 8
        (_x.obst_x, _x.obst_y,) = _get_struct_2f().unpack(str[start:end])
        self.obstacle_infos.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
