# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from obstacle_detect/RotaryArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import obstacle_detect.msg

class RotaryArray(genpy.Message):
  _md5sum = "7f4d8ffc9ddc00a08e234a44d62c525f"
  _type = "obstacle_detect/RotaryArray"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Rotary[] moving_cars

================================================================================
MSG: obstacle_detect/Rotary
float32 dis
uint8 orientation"""
  __slots__ = ['moving_cars']
  _slot_types = ['obstacle_detect/Rotary[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       moving_cars

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RotaryArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.moving_cars is None:
        self.moving_cars = []
    else:
      self.moving_cars = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.moving_cars)
      buff.write(_struct_I.pack(length))
      for val1 in self.moving_cars:
        _x = val1
        buff.write(_get_struct_fB().pack(_x.dis, _x.orientation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.moving_cars is None:
        self.moving_cars = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.moving_cars = []
      for i in range(0, length):
        val1 = obstacle_detect.msg.Rotary()
        _x = val1
        start = end
        end += 5
        (_x.dis, _x.orientation,) = _get_struct_fB().unpack(str[start:end])
        self.moving_cars.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.moving_cars)
      buff.write(_struct_I.pack(length))
      for val1 in self.moving_cars:
        _x = val1
        buff.write(_get_struct_fB().pack(_x.dis, _x.orientation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.moving_cars is None:
        self.moving_cars = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.moving_cars = []
      for i in range(0, length):
        val1 = obstacle_detect.msg.Rotary()
        _x = val1
        start = end
        end += 5
        (_x.dis, _x.orientation,) = _get_struct_fB().unpack(str[start:end])
        self.moving_cars.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_fB = None
def _get_struct_fB():
    global _struct_fB
    if _struct_fB is None:
        _struct_fB = struct.Struct("<fB")
    return _struct_fB
