// Generated by gencpp from file obstacle_detect/LidarObstacleInfoArray.msg
// DO NOT EDIT!


#ifndef OBSTACLE_DETECT_MESSAGE_LIDAROBSTACLEINFOARRAY_H
#define OBSTACLE_DETECT_MESSAGE_LIDAROBSTACLEINFOARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <obstacle_detect/LidarObstacleInfo.h>

namespace obstacle_detect
{
template <class ContainerAllocator>
struct LidarObstacleInfoArray_
{
  typedef LidarObstacleInfoArray_<ContainerAllocator> Type;

  LidarObstacleInfoArray_()
    : obstacle_infos()  {
    }
  LidarObstacleInfoArray_(const ContainerAllocator& _alloc)
    : obstacle_infos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::obstacle_detect::LidarObstacleInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::obstacle_detect::LidarObstacleInfo_<ContainerAllocator> >> _obstacle_infos_type;
  _obstacle_infos_type obstacle_infos;





  typedef boost::shared_ptr< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> const> ConstPtr;

}; // struct LidarObstacleInfoArray_

typedef ::obstacle_detect::LidarObstacleInfoArray_<std::allocator<void> > LidarObstacleInfoArray;

typedef boost::shared_ptr< ::obstacle_detect::LidarObstacleInfoArray > LidarObstacleInfoArrayPtr;
typedef boost::shared_ptr< ::obstacle_detect::LidarObstacleInfoArray const> LidarObstacleInfoArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator1> & lhs, const ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator2> & rhs)
{
  return lhs.obstacle_infos == rhs.obstacle_infos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator1> & lhs, const ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace obstacle_detect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55f01341e34384ade81bbed242fb4d66";
  }

  static const char* value(const ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55f01341e34384adULL;
  static const uint64_t static_value2 = 0xe81bbed242fb4d66ULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle_detect/LidarObstacleInfoArray";
  }

  static const char* value(const ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LidarObstacleInfo[] obstacle_infos\n"
"================================================================================\n"
"MSG: obstacle_detect/LidarObstacleInfo\n"
"float32 obst_x\n"
"float32 obst_y\n"
;
  }

  static const char* value(const ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle_infos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarObstacleInfoArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obstacle_detect::LidarObstacleInfoArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "obstacle_infos: ";
    if (v.obstacle_infos.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.obstacle_infos.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::obstacle_detect::LidarObstacleInfo_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.obstacle_infos[i]);
    }
    if (v.obstacle_infos.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLE_DETECT_MESSAGE_LIDAROBSTACLEINFOARRAY_H
