// Generated by gencpp from file obstacle_detect/ObstacleInfoArray.msg
// DO NOT EDIT!


#ifndef OBSTACLE_DETECT_MESSAGE_OBSTACLEINFOARRAY_H
#define OBSTACLE_DETECT_MESSAGE_OBSTACLEINFOARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <obstacle_detect/ObstacleInfo.h>

namespace obstacle_detect
{
template <class ContainerAllocator>
struct ObstacleInfoArray_
{
  typedef ObstacleInfoArray_<ContainerAllocator> Type;

  ObstacleInfoArray_()
    : obstacles()  {
    }
  ObstacleInfoArray_(const ContainerAllocator& _alloc)
    : obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::obstacle_detect::ObstacleInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::obstacle_detect::ObstacleInfo_<ContainerAllocator> >> _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleInfoArray_

typedef ::obstacle_detect::ObstacleInfoArray_<std::allocator<void> > ObstacleInfoArray;

typedef boost::shared_ptr< ::obstacle_detect::ObstacleInfoArray > ObstacleInfoArrayPtr;
typedef boost::shared_ptr< ::obstacle_detect::ObstacleInfoArray const> ObstacleInfoArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator1> & lhs, const ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator2> & rhs)
{
  return lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator1> & lhs, const ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace obstacle_detect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d08c5873969de4a06260eb9004c511f8";
  }

  static const char* value(const ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd08c5873969de4a0ULL;
  static const uint64_t static_value2 = 0x6260eb9004c511f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle_detect/ObstacleInfoArray";
  }

  static const char* value(const ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ObstacleInfo[] obstacles\n"
"================================================================================\n"
"MSG: obstacle_detect/ObstacleInfo\n"
"float32 distance\n"
"float32 x\n"
"float32 y\n"
"bool is_dynamic\n"
;
  }

  static const char* value(const ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleInfoArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obstacle_detect::ObstacleInfoArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "obstacles: ";
    if (v.obstacles.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::obstacle_detect::ObstacleInfo_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.obstacles[i]);
    }
    if (v.obstacles.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLE_DETECT_MESSAGE_OBSTACLEINFOARRAY_H
